[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "/Users/chenyujie/open-source/cyjseagull/FB3.0/bcos-tars-services/build"

[chain]
chain_id="chain0"
#ca_cert_path = ""
rpc_sm_ssl=false
gateway_sm_ssl=false

[[chain.rpc]]
name="agencyARpcService"
deploy_ip=["192.168.192.168"]
listen_ip="0.0.0.0"
listen_port=20200
thread_count=4
gateway_service_name = "agencyAGatewayService"

[[chain.rpc]]
name="agencyBRpcService"
deploy_ip=["192.168.192.168"]
listen_ip="0.0.0.0"
listen_port=20201
thread_count=4
gateway_service_name = "agencyBGatewayService"

[[chain.gateway]]
name="agencyAGatewayService"
deploy_ip=["192.168.192.168"]
listen_ip="0.0.0.0"
listen_port=30300
peers=["127.0.0.1:30300", "127.0.0.1:30301"]
rpc_service_name = "agencyARpcService"

[[chain.gateway]]
name="agencyBGatewayService"
deploy_ip=["192.168.192.168"]
listen_ip="0.0.0.0"
listen_port=30301
peers=["127.0.0.1:30300", "127.0.0.1:30301"]
rpc_service_name = "agencyBRpcService"


[group]
group_id="group0"
vm_type="evm"
sm_crypto=false

# the genesis config
leader_period = 5
block_tx_count_limit = 1000
consensus_timeout = 3000
consensus_type = "pbft"
gas_limit = "300000000"

[[group.deploy_info]]
# node_name = node0
microservice_node=false
deploy_ip = "192.168.192.168"
service_list='{"TxPoolService": "192.168.192.168", "FrontService": "192.168.192.168", "SchedulerService": "192.168.192.168", "PBFTService": "192.168.192.168"}'
node_count=1
rpc_service_name = "agencyARpcService"
gateway_service_name = "agencyAGatewayService"

[[group.deploy_info]]
# node_name = node0
microservice_node=false
deploy_ip = "192.168.192.168"
service_list='{"TxPoolService": "192.168.192.168", "FrontService": "192.168.192.168", "SchedulerService": "192.168.192.168", "PBFTService": "192.168.192.168"}'
node_count=1
rpc_service_name = "agencyBRpcService"
gateway_service_name = "agencyBGatewayService"
