[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "/Users/chenyujie/open-source/cyjseagull/FB3.0/bcos-tars-services/build"

[chain]
chain_id="chain0"

[rpc]
#name="chain0"
deploy_ip="192.168.192.168"
listen_ip="0.0.0.0"
listen_port=20200
sm_ssl=false
thread_count=4

[gateway]
#name="chain0"
deploy_ip="192.168.192.168"
listen_ip="0.0.0.0"
listen_port=30300
sm_ssl=false
peers=["127.0.0.1:30300", "127.0.0.1:30301"]


[group]
group_id="group0"
vm_type="evm"
sm_crypto=false

# the genesis config
leader_period = 5
block_tx_count_limit = 1000
consensus_timeout = 3000
consensus_type = "pbft"
gas_limit = "300000000"

[[group.deploy_info]]
# node_name = node0
microservice_node=false
deploy_ip = "192.168.192.168"
service_list='{"TxPoolService": "192.168.192.168", "FrontService": "192.168.192.168", "SchedulerService": "192.168.192.168", "PBFTService": "192.168.192.168"}'
node_count=2
